#! /bin/bash

# Fancy title function
title() {
  COLUMNS=$(tput cols)
  tput clear
  Y=$((($COLUMNS-${#MESSAGE})/2))
  X=1
  tput cup $X $Y
  echo -e "${MESSAGE}"
}

# exit status of previous executed command
ec=$?

# ANSI properties/colours
ESC='\033[0m'
BOLD='\033[1m'
BLUE='\033[38;34m'
BLUE_UL='\033[38;4;34m'
GREEN='\033[38;32m'
GREEN_UL='\033[38;4;32m'
CYAN='\033[38;36m'
CYAN_IL='\033[38;4;36m'
RED='\033[38;31m'
RED_UL='\033[38;4;31m'
PURPLE='\033[38;35m'
PURPLE_UL='\033[38;4;35m'
YELLOW='\033[38;33m'
YELLOW_UL='\033[38;4;33m'

# Welcome screen
MESSAGE=""$BLUE_UL"Welcome to Save OS X!"$ESC""

title
echo ''
echo -e "Here's some stuff about the project that will be echo'd\non the first screen of the script\n"
echo ''
read -p "Press [Enter] to continue"
clear


# Grab essential tools (pkgsrc & Xquartz)
cd /tmp # cd to tmp, don't want to clutter stuff up ;)
MESSAGE=""$RED_UL"Essential Tools$ESC"
title
echo ''
echo -e "This project uses "$BOLD"pkgsrc"$ESC" & "$BOLD"XQuartz"$ESC"\n"
echo ''
echo "Proceeding to download and install essential tools"
echo ''
# Download and install Git
echo "Grabbing pkgsrc from the Save OS X repo..."
echo ''
curl -s -O http://saveosx.org/packages/Darwin/bootstrap/bootstrap.tar.gz
if [[ $ec -ne ]]; then  # Check to ensure the bootstrap was retrieved successfully before trying to extract it
  echo -e '\n\n\nIt looks like there was an issue retrieving the pkgsrc bootstrap script\nPlease see above output for details'
  exit $ec
fi
cd /; sudo tar xf /tmp/bootstrap.tar.gz 2>&1 > /dev/null # extract the pkgsrc bootstrap in the root directory
echo -e '\npkgsrc downloaded and installed. Adding SmartOS & Save OS X repos...'
sudo echo "http://pkgsrc.smartos.org/packages/Darwin/2013Q2/All" >> /usr/pkg/etc/pkgin/repositories
sudo echo "http://saveosx.org/packages/Darwin/2013Q2/All" >> /usr/pkg/etc/pkgin/repositories
echo ''
echo 'Updating pkgsrc repository information'
sudo pkgin -y update
echo ''
echo 'Adding pkgsrc path to your $PATH environment'
export PATH=/usr/pkg/bin:/usr/pkg/sbin:$PATH
UPDATEDPATH=$(echo /usr/pkg/bin:/usr/pkg/sbin:$PATH)
while:
do
  print -n "Please enter the full path to your shell's rc file (.bashrc,.zshrc,.kshrc) "
  read SHELLRC
    if [ -f $SHELLRC ]; then
      PATHLINE=$(grep -n '^PATH=' $SHELLRC | cut -d ':' -f1)
      USERSPATH=$(grep '^PATH=' $SHELLRC)
      sed -i$PATHLINE 's/${USERPATH}/${UPDATEDPATH}/' $SHELLRC
      source $SHELLRC
      echo "Your shell's PATH has been updated"
      break
    else
      echo -e "It doesn't look like $SHELLRC exists, please check and try again\n"
    fi
done
# Clone the Save OS X repo
#echo ""$GREEN"Cloning the Save OS X Git repo for other scripts..."
#cd ~ ; git clone https://github.com/Phyrne/saveosx
#cd ~/saveosx
