#! /bin/bash

#  Simply put; this script "cleans up" the system services we deem unecessary.
#
#  Please, for your own sake, don't run this script if you don't have an X session set to launch upon login.
#  Don't run this script if you don't know what any of it does.
#  If you have been stupid enough to run this without an X environment to interact with your system, you can thank the guys at Apple for the '>console' login....
#
#  Should you wish to contact either myself or yrmt, we're usually on the Unix Hub irc (#unixhub @ irc.unixhub.net)
#  Alternitavely, feel free to e-mail me at calum0macrae@gmail.com
#
#  Written by phyrne 05/06/13


# Variables
UNLOAD='launchctl unload -w'
APATH='/System/Library/LaunchAgents/com.apple'
DPATH='/System/Library/LaunchDaemons/com.apple'

# User friendly prompt to ensure they have a working X environment set up prior to unloading services
clear
echo -e "This script will unload multiple Apple services that we, the creators of Save OS X, deem unecessary.\nSome of the services included will render Apple's Aqua desktop inoperable from login.\nThat's not to say that one cannot revoke these changes or run their usual Aqua Applications,\nhowever,\033[38;31m we highly recommend you have a working X environment set to launch upon login\033[39m."
echo
echo -e "\033[38;33mPlease ensure you have fully read the documentation provided on the Save OS X website.\033[39m"
echo

while :
do
read -r -p "Are you sure you want to run this script? [y/n]" ANSWER
  case $ANSWER in
      [yY][eE][sS]|[yY])
        echo
        echo "Disabling unecessary services"
        break
        ;;
      [nN][oO]|[nN])
        echo
        echo "Exiting..."
        exit 1
        break
        ;;
      *)
        echo "Please answer yes or no..."
  esac
done

# List of services that will be disabled by this script
AGENTS="$APATH.UserEventAgent-Aqua
$APATH.ZoomWindow
$APATH.weibod
$APATH.WebKit.PluginAgent
$APATH.VoiceOver
$APATH.UserNotificationCenterAgent
$APATH.UserNotificationCenterAgent-LoginWindow
$APATH.unmountassistant.useragent
$APATH.universalaccessd
$APATH.universalaccesscontrol
$APATH.ubd
$APATH.twitterd
$APATH.TMLaunchAgent
$APATH.tiswitcher
$APATH.talagent
$APATH.SystemUIServer
$APATH.systemprofiler
$APATH.syncservices.uihandler
$APATH.syncservices.SyncServer
$APATH.syncdefaultsd
$APATH.SubmitDiagInfo
$APATH.SubmitDiagInfo.xpc
$APATH.storeagent
$APATH.store_helper
$APATH.spindump_agent
$APATH.speech.voiceinstallerd
$APATH.speech.synthesisserver
$APATH.speech.recognitionserver
$APATH.speech.feedbackservicesserver
$APATH.SocialPushAgent
$APATH.sociald
$APATH.ServiceManagement.LoginItems
$APATH.scrod
$APATH.screensharing
$APATH.ScreenReaderUIServer
$APATH.scopedbookmarkagent.xpc
$APATH.safaridavclient
$APATH.ReportGPURestart
$APATH.ReportCrash.Self
$APATH.ReportCrash
$APATH.RemoteDesktop.agent
$APATH.ReclaimSpaceAgent
$APATH.rcd
$APATH.quicklook.ui.helper
$APATH.quicklook
$APATH.quicklook.config
$APATH.quicklook.32bit
$APATH.PubSub.Agent
$APATH.printuitool.agent
$APATH.printtool.agent
$APATH.pictd
$APATH.PCIESlotCheck
$APATH.pbs
$APATH.parentalcontrols.check
$APATH.PackageKit.InstallStatus
$APATH.notificationcenterui
$APATH.NetworkDiagnostics
$APATH.NetworkBrowserAgent
$APATH.netauth.user.gui
$APATH.mrt.uiagent
$APATH.midiserver
$APATH.metadata.mdwrite
$APATH.mdmclient.agent
$APATH.maspushagent
$APATH.marcoagent
$APATH.lookupd
$APATH.locationmenu
$APATH.librariand
$APATH.LaunchServices.lsboxd
$APATH.java.updateSharing
$APATH.java.InstallOnDemand
$APATH.isst
$APATH.installd.user
$APATH.imklaunchagent
$APATH.imagent
$APATH.iChat.Theater
$APATH.helpd
$APATH.gamed
$APATH.FTCleanup
$APATH.FontWorker
$APATH.FontValidator
$APATH.FontValidatorConduit
$APATH.FontRegistryUIAgent
$APATH.fontd.useragent
$APATH.findmymacmessenger
$APATH.Finder
$APATH.familycontrols.useragent
$APATH.Dock
$APATH.DiskArbitrationAgent
$APATH.csuseragent
$APATH.coreservices.uiagent
$APATH.coreservices.appleid.authentication
$APATH.CoreRAIDAgent
$APATH.CoreLocationAgent
$APATH.coredata.externalrecordswriter
$APATH.cookied
$APATH.ContainerRepairAgent
$APATH.cfnetwork.cfnetworkagent
$APATH.cfnetwork.AuthBrokerAgent
$APATH.CalendarAgent
$APATH.btsa
$APATH.bluetoothUIServer
$APATH.bluetoothAudioAgent
$APATH.BezelUI
$APATH.assistantd
$APATH.assistant_service
$APATH.apsctl
$APATH.appstoreupdateagent
$APATH.AOSPushRelay
$APATH.AOSNotificationOSX
$APATH.aos.migrate
$APATH.alf.useragent
$APATH.AirPortBaseStationAgent
$APATH.AirPlayUIAgent
$APATH.afpstat
$APATH.AddressBook.SourceSync
$APATH.AddressBook.AssistantService
$APATH.AddressBook.abd
$APATH.accountsd
$APATH.xmigrationhelper.user
$APATH.TrustEvaluationAgent
$APATH.tccd
$APATH.netauth.user.auth
$APATH.mdworker.single
$APATH.mdworker.shared
$APATH.mdworker.mail
$APATH.mdworker.lsb
$APATH.mdworker.isolation
$APATH.mdworker.bundles
$APATH.mdworker.32bit
$APATH.KerberosHelper.LKDCHelper
$APATH.FileSyncAgent.PHD
$APATH.cvmsCompAgent_x86_64_1
$APATH.cvmsCompAgent_x86_64
$APATH.cvmsCompAgent_i386_1
$APATH.cvmsCompAgent_i386
$APATH.cfprefsd.xpc.agent"

# for loop that disables the above list of services
for agent in $AGENTS
  do
    echo -e "Unloading \033[38;34m$(echo $agent | cut -d '/' -f5)\033[39m"
    $UNLOAD $agent.plist 2> /dev/null
done

echo
echo -e "\033[38;32mComplete!\033[39m"
