#! /bin/bash

#  Simply put; this script "cleans up" the system services we deem unecessary.
#
#  Please, for your own sake, don't run this script if you don't have an X session set to launch upon login.
#  Simply don't run this script if you don't know what any of it does.
#  If you have been stupid enough to run this without an X environment to interact with your system, you can thank the guys at Apple for the '>console' login....
#
#  Should you wish to contact either myself or Beastie, we're usually on the Unix Hub irc (#unixhub @ irc.unixhub.net)
#  Alternitavely, feel free to e-mail me at calum0macrae@gmail.com
#
#  Written by phyrne 05/06/13

UNLOAD='launchctl unload -w'
APATH='/System/Library/LaunchAgents/com.apple'
DPATH='/System/Library/LaunchDaemons/com.apple'

AGENTS="$APATH.UserEventAgent-Aqua
$APATH.ZoomWindow
$APATH.weibod
$APATH.WebKit.PluginAgent
$APATH.VoiceOver
$APATH.UserNotificationCenterAgent
$APATH.UserNotificationCenterAgent-LoginWindow
$APATH.unmountassistant.useragent
$APATH.universalaccessd
$APATH.universalaccesscontrol
$APATH.ubd
$APATH.twitterd
$APATH.TMLaunchAgent
$APATH.tiswitcher
$APATH.talagent
$APATH.SystemUIServer
$APATH.systemprofiler
$APATH.syncservices.uihandler
$APATH.syncservices.SyncServer
$APATH.syncdefaultsd
$APATH.SubmitDiagInfo
$APATH.SubmitDiagInfo.xpc
$APATH.storeagent
$APATH.store_helper
$APATH.spindump_agent
$APATH.speech.voiceinstallerd
$APATH.speech.synthesisserver
$APATH.speech.recognitionserver
$APATH.speech.feedbackservicesserver
$APATH.SocialPushAgent
$APATH.sociald
$APATH.ServiceManagement.LoginItems
$APATH.scrod
$APATH.screensharing
$APATH.ScreenReaderUIServer
$APATH.scopedbookmarkagent.xpc
$APATH.safaridavclient
$APATH.ReportGPURestart
$APATH.ReportCrash.Self
$APATH.ReportCrash
$APATH.RemoteDesktop.agent
$APATH.ReclaimSpaceAgent
$APATH.rcd
$APATH.quicklook.ui.helper
$APATH.quicklook
$APATH.quicklook.config
$APATH.quicklook.32bit
$APATH.PubSub.Agent
$APATH.printuitool.agent
$APATH.printtool.agent
$APATH.pictd
$APATH.PCIESlotCheck
$APATH.pbs
$APATH.parentalcontrols.check
$APATH.PackageKit.InstallStatus
$APATH.notificationcenterui
$APATH.NetworkDiagnostics
$APATH.NetworkBrowserAgent
$APATH.netauth.user.gui
$APATH.mrt.uiagent
$APATH.midiserver
$APATH.metadata.mdwrite
$APATH.mdmclient.agent
$APATH.maspushagent
$APATH.marcoagent
$APATH.lookupd
$APATH.locationmenu
$APATH.librariand
$APATH.LaunchServices.lsboxd
$APATH.java.updateSharing
$APATH.java.InstallOnDemand
$APATH.isst
$APATH.installd.user
$APATH.imklaunchagent
$APATH.imagent
$APATH.iChat.Theater
$APATH.helpd
$APATH.gamed
$APATH.FTCleanup
$APATH.FontWorker
$APATH.FontValidator
$APATH.FontValidatorConduit
$APATH.FontRegistryUIAgent
$APATH.fontd.useragent
$APATH.findmymacmessenger
$APATH.Finder
$APATH.familycontrols.useragent
$APATH.Dock
$APATH.DiskArbitrationAgent
$APATH.csuseragent
$APATH.coreservices.uiagent
$APATH.coreservices.appleid.authentication
$APATH.CoreRAIDAgent
$APATH.CoreLocationAgent
$APATH.coredata.externalrecordswriter
$APATH.cookied
$APATH.ContainerRepairAgent
$APATH.cfnetwork.cfnetworkagent
$APATH.cfnetwork.AuthBrokerAgent
$APATH.CalendarAgent
$APATH.btsa
$APATH.bluetoothUIServer
$APATH.bluetoothAudioAgent
$APATH.BezelUI
$APATH.assistantd
$APATH.assistant_service
$APATH.apsctl
$APATH.appstoreupdateagent
$APATH.AOSPushRelay
$APATH.AOSNotificationOSX
$APATH.aos.migrate
$APATH.alf.useragent
$APATH.AirPortBaseStationAgent
$APATH.AirPlayUIAgent
$APATH.afpstat
$APATH.AddressBook.SourceSync
$APATH.AddressBook.AssistantService
$APATH.AddressBook.abd
$APATH.accountsd
$APATH.xmigrationhelper.user
$APATH.TrustEvaluationAgent
$APATH.tccd
$APATH.netauth.user.auth
$APATH.mdworker.single
$APATH.mdworker.shared
$APATH.mdworker.mail
$APATH.mdworker.lsb
$APATH.mdworker.isolation
$APATH.mdworker.bundles
$APATH.mdworker.32bit
$APATH.KerberosHelper.LKDCHelper
$APATH.FileSyncAgent.PHD
$APATH.cvmsCompAgent_x86_64_1
$APATH.cvmsCompAgent_x86_64
$APATH.cvmsCompAgent_i386_1
$APATH.cvmsCompAgent_i386
$APATH.cfprefsd.xpc.agent"

for a in $AGENTS
  do
    echo "Unloading $(echo $a | cut -d '/' -f5)"
    $UNLOAD $a.plist 2> /dev/null
done

echo
echo "Complete!"
