#! /bin/bash

#  Simply put; this script "cleans up" the system services we deem unecessary.
#
#
#  Written by phyrne 05/06/13

# Fancy title function
title() {
  COLUMNS=$(tput cols)
  tput clear
  Y=$((($COLUMNS-${#MESSAGE})/2))
  X=1
  tput cup $X $Y
  echo -e "${MESSAGE}"
}

# Variables
UNLOAD='launchctl unload -w'
APATH='/System/Library/LaunchAgents/com.apple'
DPATH='/System/Library/LaunchDaemons/com.apple'

# ANSI properties/colours
ESC='\033[0m'
GREEN='\033[38;32m'
RED_UL='\033[38;4;31m'
YELLOW='\033[38;33m'

# User friendly prompt to ensure they have a working X environment set up prior to unloading services
clear
MESSAGE=""$RED_UL"Daemon Cleanup"$ESC""
echo
echo -e "This script will unload multiple Apple services that we, the creators of Save OS X, deem unecessary."
echo ''
echo -e "Should you wish to load any that we have disabled, simply run the below command:\n"
echo -e ""$YELLOW"launchctl load -w /System/Library/LaunchAgents/*name-of-service*"$ESC""
echo ''
while :
do
read -r -p "Press [Enter] to proceed... "
  
# List of services that will be disabled by this script
AGENTS="$APATH.UserEventAgent-Aqua
$APATH.ZoomWindow
$APATH.weibod
$APATH.WebKit.PluginAgent
$APATH.VoiceOver
$APATH.UserNotificationCenterAgent-LoginWindow
$APATH.unmountassistant.useragent
$APATH.universalaccessd
$APATH.universalaccesscontrol
$APATH.ubd
$APATH.twitterd
$APATH.TMLaunchAgent
$APATH.tiswitcher
$APATH.talagent
$APATH.systemprofiler
$APATH.syncservices.uihandler
$APATH.syncservices.SyncServer
$APATH.syncdefaultsd
$APATH.SubmitDiagInfo
$APATH.SubmitDiagInfo.xpc
$APATH.storeagent
$APATH.store_helper
$APATH.spindump_agent
$APATH.speech.voiceinstallerd
$APATH.speech.synthesisserver
$APATH.speech.recognitionserver
$APATH.speech.feedbackservicesserver
$APATH.SocialPushAgent
$APATH.sociald
$APATH.ServiceManagement.LoginItems
$APATH.scrod
$APATH.screensharing
$APATH.ScreenReaderUIServer
$APATH.scopedbookmarkagent.xpc
$APATH.safaridavclient
$APATH.ReportGPURestart
$APATH.ReportCrash.Self
$APATH.ReportCrash
$APATH.RemoteDesktop.agent
$APATH.ReclaimSpaceAgent
$APATH.rcd
$APATH.quicklook.ui.helper
$APATH.quicklook
$APATH.quicklook.config
$APATH.quicklook.32bit
$APATH.PubSub.Agent
$APATH.printuitool.agent
$APATH.printtool.agent
$APATH.pictd
$APATH.PCIESlotCheck
$APATH.pbs
$APATH.parentalcontrols.check
$APATH.PackageKit.InstallStatus
$APATH.notificationcenterui
$APATH.NetworkDiagnostics
$APATH.NetworkBrowserAgent
$APATH.netauth.user.gui
$APATH.mrt.uiagent
$APATH.midiserver
$APATH.metadata.mdwrite
$APATH.mdmclient.agent
$APATH.maspushagent
$APATH.marcoagent
$APATH.lookupd
$APATH.locationmenu
$APATH.librariand
$APATH.LaunchServices.lsboxd
$APATH.java.updateSharing
$APATH.java.InstallOnDemand
$APATH.isst
$APATH.installd.user
$APATH.imklaunchagent
$APATH.imagent
$APATH.iChat.Theater
$APATH.helpd
$APATH.gamed
$APATH.FTCleanup
$APATH.FontWorker
$APATH.FontValidator
$APATH.FontValidatorConduit
$APATH.FontRegistryUIAgent
$APATH.fontd.useragent
$APATH.findmymacmessenger
$APATH.Finder
$APATH.familycontrols.useragent
$APATH.DiskArbitrationAgent
$APATH.csuseragent
$APATH.coreservices.uiagent
$APATH.coreservices.appleid.authentication
$APATH.CoreRAIDAgent
$APATH.CoreLocationAgent
$APATH.coredata.externalrecordswriter
$APATH.cookied
$APATH.ContainerRepairAgent
$APATH.cfnetwork.cfnetworkagent
$APATH.cfnetwork.AuthBrokerAgent
$APATH.CalendarAgent
$APATH.btsa
$APATH.bluetoothUIServer
$APATH.bluetoothAudioAgent
$APATH.assistantd
$APATH.assistant_service
$APATH.apsctl
$APATH.appstoreupdateagent
$APATH.AOSPushRelay
$APATH.AOSNotificationOSX
$APATH.aos.migrate
$APATH.alf.useragent
$APATH.AirPortBaseStationAgent
$APATH.AirPlayUIAgent
$APATH.afpstat
$APATH.AddressBook.SourceSync
$APATH.AddressBook.AssistantService
$APATH.AddressBook.abd
$APATH.accountsd
$APATH.xmigrationhelper.user
$APATH.TrustEvaluationAgent
$APATH.tccd
$APATH.netauth.user.auth
$APATH.mdworker.single
$APATH.mdworker.shared
$APATH.mdworker.mail
$APATH.mdworker.lsb
$APATH.mdworker.isolation
$APATH.mdworker.bundles
$APATH.mdworker.32bit
$APATH.KerberosHelper.LKDCHelper
$APATH.FileSyncAgent.PHD
$APATH.cvmsCompAgent_x86_64_1
$APATH.cvmsCompAgent_x86_64
$APATH.cvmsCompAgent_i386_1
$APATH.cvmsCompAgent_i386
$APATH.cfprefsd.xpc.agent"

# for loop that disables the above list of services
for agent in $AGENTS
  do
    echo -e "Unloading \033[38;34m$(echo $agent | cut -d '/' -f5)\033[39m"
    $UNLOAD $agent.plist 2> /dev/null
done

echo
echo -e ""$GREEN"Complete!"$GREEN"\n"
read -r -p "Press [Enter] to continue..."
