#! /bin/bash

#
# - Do NOT run this script at this point. It is under development. If you run this script right now, you will render your system unusable....
#


# Check for root
if [[ $EUID -ne  0 ]]; then
  echo "This script must be run as root!"
  exit 1
fi

# Disable hibernation
echo "Disabling hibernation"
pmset -a hibernatemode 0
rm -f /pivate/var/vm/sleepimage

# Remove speech files
echo "Removing speech files"
rm -f /System/Library/Voices/*

# Remove log files & caches
echo "Removing logs, tmp files & caches"
rm -rf /private/var/{log,folders}/* # General logs & quick look caches
rm -rf /private/var/tmp/TM* # tmp files
rm -rf /Library/Caches/* # General caches

# Remove update files
echo "Removing update files"
rm -rf /Library/Updates/*

# Commented out, as this is currently causing problems

# Render spotlight unusable
#echo "Disabling Spotlight"
#mdutil -a -v -i off > /dev/null 2>&1
#chmod 000 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/        ↳ Support/* > /dev/null 2>&1
#launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist > /dev/null 2>&1
#mv /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search{,.disabled} > /dev/null 2>&1
#chmod -x /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search.disabled > /dev/null 2>&1
#mv /System/Library/CoreServices/Search.bundle{,.disabled} > /dev/null 2>&1
#killall SystemUIServer > /dev/null 2>&1


# Confirm function to prompt user for decision
confirm() {
    case $ANSWER in
      [yY][eE][sS]|[yY])
        if [ "$2" = "-d" ]; then
          launchctl unload -w $DAEMONPATH > /dev/null 2>&1
          echo "Removing $1"
        fi
          echo "Removing $1"
          rm -rf $FILEPATH
          break
          ;;
      [nN][oO]|[nN])
        echo "Leaving $1 intact"
        break
        ;;
      *)
        echo "Please answer yes or no... "
    esac
}


# Emacs
FILEPATH=/usr/{bin,libexec,share/info}/emacs,/opt/local/share/emacs

while :
do
  read -r -p "Would you like to remove the Emacs editor [y/n]? " ANSWER
  confirm Emacs
done

# Non-English dictionaries
FILEPATH=/Library/Dictionaries/*.dictionary

while :
do
  read -r -p "Would you like to remove unecessary dictionaries? [y/n] " ANSWER
  confirm dictionaries
done

# Swap
DAEMONPATH=/System/Library/LaunchDaemons/com.apple.dynamic_pager.plist
FILEPATH=/private/var/vm/swapfile*

while :
do
  read -r -p "Would you like to disable swapping [y/n]? " ANSWER
  confirm swap -d
done
