#! /bin/bash

# Copyright © 2014 Calum MacRae
# Use of this source code is governed by an ISC
# license that can be found in the LICENSE file.

# Common resources to be shared between the 
# Save OS X setup scripts

#
# - Sanity checks
#

# Ensure the user is running this script on OS X
if [ $(uname -s) != "Darwin" ]; then
    echo "This script is for use with OS X!"
    exit 1
fi

# Ensure the user is running on an x86_64 system
if [ $(uname -m) != 'x86_64' ] ; then
 echo ""$RED_UL"We only support x86_64 systems!"$ESC""
 exit 1
fi

# Ensure script is not being run with root privileges
if [ $EUID -eq 0 ]; then
   echo "Please don't run this script with root priveleges!"
   exit 1
fi

# Ensure script is being run in Terminal.app (due to launchctl restrictions)
if [[ $TERM_PROGRAM != "Apple_Terminal" || -z $TERM_PROGRAM ]]; then
  echo "This script must be run in Apple's Terminal.app"
  echo "Please re-run this script in Terminal.app..."
  exit 1
fi

#
# - Functions
#

# Fancy title function
title() {
  local MESSAGE=$1
  local COLUMNS=$(tput cols)
  tput clear
  local Y=$((($COLUMNS-${#MESSAGE})/2))
  local X=1
  tput cup $X $Y
  echo -e "${MESSAGE}"
}

# Safe run function to ensure commands are executed successfully
saferun() {
  typeset cmnd="$*"
  typeset ret_code

  eval  $cmnd
  ret_code=$?
  
  if [ $ret_code != 0 ]; then
     echo -e ""$RED_UL"\n\nIt looks like there was an issue running: $*"$ESC"\n\nExiting..."
     exit $?
  fi
}

#
# - Common variables
#

# ANSI properties/colours
ESC='\033[0m'
BLUE='\033[38;34m'
BLUE_UL='\033[38;4;34m'
GREEN='\033[38;32m'
GREEN_UL='\033[38;4;32m'
RED='\033[38;31m'
RED_UL='\033[38;4;31m'
YELLOW='\033[38;33m'
YELLOW_UL='\033[38;4;33m'

# Set user's library path
LIB_PATH=/Users/$USER/Library/LaunchAgents
