#! /bin/bash

# This is a script to create scripts and plists to launch X upon user login to run in a seamless manner along side the Aqua desktop
#
# Written by cmacrae 21/07/13

# Check for root
if [ $EUID -ne 0 ]; then
  echo "This script must be run as root!"
  exit 1
fi

# Set library path
LIB_PATH=/Users/$USER/Library/LaunchAgents

# Fancy title function
title() {
  COLUMNS=$(tput cols)
  tput clear
  Y=$((($COLUMNS-${#MESSAGE})/2))
  X=1
  tput cup $X $Y
  echo -e "${MESSAGE}"
}

# ANSI properties/colours
ESC='\033[0m'
BOLD='\033[1m'
BLUE='\033[38;34m'
BLUE_UL='\033[38;4;34m'
GREEN='\033[38;32m'
GREEN_UL='\033[38;4;32m'
CYAN='\033[38;36m'
CYAN_UL='\033[38;4;36m'
RED='\033[38;31m'
RED_UL='\033[38;4;31m'
PURPLE='\033[38;35m'
PURPLE_UL='\033[38;4;35m'
YELLOW='\033[38;33m'
YELLOW_UL='\033[38;4;33m'

# Title
clear
MESSAGE=""$BLUE_UL"X11 Setup"$ESC""
title
cat << EOM
Please understand that you will need to set up your X11 environment yourself.
This is done as it would be on any other OS, simply install your
window manager/desktop environment of choice (through pkgin), set up your ~/.xinitrc,
plus any other configurations your window manager/desktop environment may need
and you should be all set!

EOM

read -r -p "Press [Enter] to continue..."
echo ''

# Create a service file to be enabled to run at login to start X with the above script
echo -e "Setting up X11 launchd service..."
if [ ! -d $LIBPATH ]; then
  mkdir -p $LIBPATH
  chown $USER:staff $LIBPATH
fi

cp -f /tmp/saveosx/org.saveosx.startx.plist $LIB_PATH/
chown $USER:staff $LIB_PATH/org.saveosx.startx.plist
chmod 644 $LIB_PATH/org.saveosx.startx.plist

# Ask user if they would like to disable Finder
while :
do
  read -r -p "Would you like to disable Finder's launch upon login? [y/n] " ANSWER
    case $ANSWER in
      [yY][eE][sS]|[yY])
        echo -e "\nOK, disabling Finder..."
        defaults write com.apple.finder QuitMenuItem -bool YES
        sudo -u $USER launchctl unload -w /System/Library/LaunchAgents/com.apple.Finder.plist
        break
        ;;
      [nN][oO]|[nN])
        echo -e "\nLeaving Finder alone..."
        break
        ;; 
      *)
        echo "Please answer yes or no..."
    esac
done

# Permanently hide dock option
while :
  do
    read -r -p "Would you like to permanently hide the dock? [y/n] " ANSWER
      case $ANSWER in
        [yY][eE][sS]|[yY])
          echo -e "\nOK, hiding Dock.app..."
          defaults write com.apple.dock autohide-time-modifier -int 10000000000
          defaults write com.apple.dock no-bouncing -bool TRUE
          killall Dock
          break
          ;;
        [nN][oO]|[nN])
          echo -e "\nLeaving Dock.app alone..."
          break
          ;; 
        *)
          echo "Please answer yes or no..."
      esac
done

# Hide menu bar for XQuartz
echo -e "Configuring XQuartz to be seemless..."
mv /Applications/Utilities/XQuartz.app/Contents/Info.plist{,.orig} ; cp -f /tmp/saveosx/xquartz.plist /Applications/Utilities/XQuartz.app/Contents/Info.plist

# Set XQuartz to launch at login
echo ''
echo -e "Necessary X files have been created.\n"$YELLOW"Setting X to launch at login"$ESC""
sudo -u $USER launchctl load -w $LIB_PATH/org.saveosx.startx.plist
echo ''
echo -e ""$GREEN"Complete!"$ESC""
read -r -p "Press [Enter] to continue... "
